image: hseeberger/scala-sbt

stages:
  - test

before_script:
  - sbt sbtVersion

test:
  stage: test
  script:
    - sbt clean scalastyle test:scalastyle scalafmtCheck scalafmtSbtCheck coverage test coverageReport
