image: openjdk:12

before_script:
  - curl https://bintray.com/sbt/rpm/rpm | tee /etc/yum.repos.d/bintray-sbt-rpm.repo
  - yum install --assumeyes sbt
  - sbt update

test:
  script:
    - sbt clean scalastyle test:scalastyle scalafmtCheckAll coverage test coverageReport
