image: "hseeberger/scala-sbt:11.0.13_1.5.5_2.13.7"

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"

cache:
  # https://leonard.io/blog/2017/05/gitlab-ci-caching-for-sbt-projects/
  # if you want to have a separate cache per branch, uncomment the next line
  key: ${CI_COMMIT_REF_SLUG}
  untracked: true
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/target"
    - "sbt-cache/coursier"

build:
  stage: build
  script:
    - sbt clean scalafmtCheckAll coverage test coverageReport
